# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod verify
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
blobs:
  - provider: s3
    region: us-west-2
    bucket: effx-cli
    folder: "releases/{{ .Version }}"
  - provider: s3
    region: us-west-2
    bucket: effx-cli
    folder: "releases/latest"
checksum:
  name_template: 'checksums.txt'
  algorithm: md5
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
