---
kind: Service
apiVersion: effx.io/v1
metadata:
  name: jwt service
  description: grpc service for dealing with tokens
  annotations:
    effx.io/owned-by: authentication team
  labels:
    group: auth
    tier: "1.13.5"
    go: "1.13.5"
spec:
  contactInformation:
    email: auth@effx.com
    chat:
      name: effx
      url: https://effx.slack.com/archives/CJV3H8Z41
    on_call:
      name: pagerduty schedule
      url: https://effxio.pagerduty.com/schedules#PJEA3VC
  linkGroups:
    - name: dashboard
      links:
        - name: datadog
          url: https://app.datadoghq.com/apm/service/trugut/grpc.server?env=prod
    - name: runbook
      links:
        - name: on call runbook
          url: https://www.notion.so/effx/general-on-call-69541dee6da64c87b70b1cc78e293cb8

